### ISSUE TITLE
Module crashes on load

### ISSUE THREAD

**Issue by afawaz2** [vladaman/freescout-saml2#3]
When enabling the SAML module we get an error with the following message

`WARNING: [pool www] child 2319 said into stderr: "NOTICE: PHP message: PHP Fatal error: Cannot declare class Modules\Saml\Providers\SamlServiceProvider, because the name is already in use in /data/Modules/Saml/Providers/SamlServiceProvider.php on line 0"`

**Comment by cescarsega** [comment]
This is also happening for me too.

**Comment by cescarsega** [comment]
This is also happening for me too.

**Comment by vladaman** [comment]
Thanks for reporting @afawaz2 and @cescarsega ! I have updated a code. Issue was related to a wrong namespace.
